services:
  db:
    image: postgres:11.8-alpine
    volumes:
      - service-datastore:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - db-net
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB:       payroll-db
      POSTGRES_USER:     payroll-user
      POSTGRES_PASSWORD: payroll-pass
      POSTGRES_HOST_AUTH_METHOD: trust